spring: 
  profiles: 
    active: 
    - dev
---
spring: 
  profilesdev:      #开发环境
  application: 
    name: microservice-config-yzm-dev
---
spring: 
  profiles: test    #测试环境
  application: 
    name: microservice-config-yzm-test