spring: 
  profiles: 
    active: 
      -dev
---
server:
  port: 7001

spring:
  profiles: dev
  application: 
    name: microservice-config-eureka-client

eureka: 
  instance: 
    hostname: localhost
  client: 
    register-with-eureka: false #当前的eureka-Server自己不注册进服务列表
    fetch-registry: false #不通过eureka获取注册信息
    service-url: 
      defauleZone: http://localhost:7001/eureka/
---
server:
  port: 7001

spring:
  profiles: test
  application: 
    name: microservice-config-eureka-client

eureka: 
  instance: 
    hostname: localhost
  client: 
    register-with-eureka: false #当前的eureka-Server自己不注册进服务列表
    fetch-registry: false #不通过eureka获取注册信息
    service-url: 
      defauleZone: http://localhost:7001/eureka/
